import assert from 'node:assert/strict';
import { test } from 'node:test';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
test('compiled Azure resources preserve runtime, storage, identity and cost contracts', { skip: !process.env.BICEP_CLI && 'Set BICEP_CLI to an existing compiler for offline resource checks.' }, () => {
  const result = spawnSync(process.env.BICEP_CLI!, ['build', fileURLToPath(new URL('../infra/main.bicep', import.meta.url)), '--stdout'], { encoding: 'utf8' });
  assert.equal(result.status, 0, result.stderr);
  assert.equal(result.stderr, '');
  const arm = JSON.parse(result.stdout);
  const resources = arm.resources as any[];
  const one = (type: string) => {
    const matches = resources.filter(r => r.type === type);
    assert.equal(matches.length, 1, type);
    return matches[0];
  };
  const cosmos = one('Microsoft.DocumentDB/databaseAccounts').properties;
  assert.equal(cosmos.consistencyPolicy.defaultConsistencyLevel, 'Strong');
  assert.equal(cosmos.enableFreeTier, true);
  assert.equal(cosmos.disableLocalAuth, true);
  assert.equal(cosmos.locations.length, 1);
  assert.equal(cosmos.enableMultipleWriteLocations, false);
  assert.equal(cosmos.capacity.totalThroughputLimit, 1000);
  assert.deepEqual(cosmos.backupPolicy.periodicModeProperties, { backupIntervalInMinutes: 240, backupRetentionIntervalInHours: 8 });
  assert.equal(one('Microsoft.DocumentDB/databaseAccounts/sqlDatabases').properties.options.throughput, 1000);
  const containers = resources.filter(r => r.type.endsWith('/containers'));
  assert.equal(containers.length, 1);
  assert.equal(containers[0].copy.count, "[length(variables('containers'))]");
  assert.equal(containers[0].properties.resource.defaultTtl, -1);
  assert.deepEqual(containers[0].properties.resource.partitionKey.paths, ["[variables('containers')[copyIndex()].partitionKey]"]);
  assert.deepEqual(containers[0].properties.options, {});
  assert.deepEqual(arm.variables.containers, [{ name: 'accounts', partitionKey: '/accountId' }, { name: 'setups', partitionKey: '/setupId' }, { name: 'identities', partitionKey: '/id' }]);
  const roles = resources.filter(r => r.type.endsWith('/sqlRoleDefinitions'));
  assert.equal(roles.length, 2);
  const metadata = roles.find(r => r.properties.permissions[0].dataActions.length === 1);
  assert.deepEqual(metadata.properties.permissions[0].dataActions, ['Microsoft.DocumentDB/databaseAccounts/readMetadata']);
  const data = roles.find(r => r !== metadata);
  assert.equal(data.properties.permissions[0].dataActions.length, 8);
  for (const action of ['executeQuery', 'readChangeFeed']) assert.ok(data.properties.permissions[0].dataActions.some((a: string) => a.endsWith('/' + action)));
  assert.equal(data.properties.assignableScopes[0], "[variables('databaseScope')]");
  assert.ok(arm.variables.databaseScope.includes('/dbs/'));
  const assignments = resources.filter(r => r.type.endsWith('/sqlRoleAssignments'));
  assert.equal(assignments.length, 2);
  assert.ok(assignments.every(r => r.properties.principalId.includes('Microsoft.ManagedIdentity/userAssignedIdentities')));
  assert.ok(assignments.some(r => r.properties.scope === "[variables('databaseScope')]"));
  const app = one('Microsoft.App/containerApps');
  assert.equal(app.identity.type, 'UserAssigned');
  assert.equal(app.properties.configuration.activeRevisionsMode, 'Single');
  assert.deepEqual(app.properties.configuration.ingress, { external: true, targetPort: 8080, allowInsecure: false, transport: 'auto' });
  const template = app.properties.template;
  assert.equal(template.terminationGracePeriodSeconds, 30);
  assert.equal(template.scale.minReplicas, 0);
  assert.equal(template.scale.maxReplicas, 2);
  const container = template.containers[0];
  assert.equal(container.image, "[parameters('image')]");
  assert.deepEqual(container.resources, { cpu: "[json('0.25')]", memory: '0.5Gi' });
  assert.deepEqual(container.probes.map((p: any) => [p.type, p.httpGet.path, p.httpGet.port]), [['Startup', '/readyz', 8080], ['Readiness', '/readyz', 8080], ['Liveness', '/v1/health', 8080]]);
  assert.equal(container.probes[0].failureThreshold, 10);
  assert.equal(container.probes[0].periodSeconds, 20);
  assert.ok(container.env.find((e: any) => e.name.endsWith('MANAGED_IDENTITY_CLIENT_ID')).value.includes('.clientId'));
  assert.equal(container.env.find((e: any) => e.name.endsWith('OPEN_SIGNUP')).value, "[if(parameters('openSignup'), 'true', 'false')]");
  assert.ok(!JSON.stringify(container.env).includes('FEDERATED'));
  const workspace = one('Microsoft.OperationalInsights/workspaces').properties;
  assert.equal(workspace.retentionInDays, 30);
  assert.equal(workspace.features.disableLocalAuth, true);
  assert.equal(workspace.workspaceCapping.dailyQuotaGb, 1);
  assert.equal(one('Microsoft.App/managedEnvironments').properties.appLogsConfiguration.destination, 'azure-monitor');
  const diagnostic = one('Microsoft.Insights/diagnosticSettings').properties;
  assert.deepEqual(diagnostic.logs.map((l: any) => l.category), ['ContainerAppConsoleLogs', 'ContainerAppSystemLogs']);
  assert.ok(diagnostic.workspaceId.includes('Microsoft.OperationalInsights/workspaces'));
  const budget = one('Microsoft.Consumption/budgets').properties;
  assert.equal(budget.timeGrain, 'Monthly');
  assert.deepEqual(Object.values(budget.notifications).map((n: any) => [n.thresholdType, n.threshold]), [['Actual', 50], ['Actual', 80], ['Actual', 100], ['Forecasted', 100]]);
  assert.ok(!JSON.stringify(arm).includes('autoscale'));
  assert.ok(!JSON.stringify(arm).includes('listKeys'));
  assert.deepEqual(Object.keys(arm.outputs), ['endpoint', 'appName', 'runtimeIdentityResourceId', 'runtimeIdentityClientId', 'runtimeIdentityPrincipalId']);
});
