#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
# A new task-owned public snapshot avoids overwriting any previous setup values.
ENV_FILE=$(mktemp "$SCRIPT_DIR/owner-public.XXXXXX")
capture_public() {
  local key="$1" prompt="$2" value
  ask "$key" "$prompt"
  value="${!key}"
  case "$key" in
    AZURE_CLIENT_ID|AZURE_TENANT_ID|AZURE_SUBSCRIPTION_ID)
      [[ "$value" =~ ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$ && ${#value} -eq 36 ]] || { warn "Expected a lowercase public UUID."; exit 1; } ;;
    AZURE_RESOURCE_GROUP)
      [[ "$value" =~ ^[a-zA-Z0-9][a-zA-Z0-9_-]{0,89}$ ]] || { warn "Expected a simple public resource-group name."; exit 1; } ;;
    LOCATION)
      [[ "$value" =~ ^[a-z][a-z0-9]{1,31}$ ]] || { warn "Expected a compact Azure region code."; exit 1; } ;;
    GITHUB_CLIENT_ID)
      [[ "$value" =~ ^[A-Za-z0-9_]{1,100}$ ]] || { warn "Expected a public GitHub OAuth client ID."; exit 1; } ;;
    *) exit 1 ;;
  esac
  write_env "$key" "$value"
}

banner "Hosted service owner setup"
note "This script opens documentation and captures public values only. You make every external change manually."
note "Each run creates a fresh public snapshot; do not paste credentials, tokens or secrets."

stage "Subscription, region and free-tier eligibility"
open_url "https://portal.azure.com/#view/Microsoft_Azure_Billing/SubscriptionsBlade"
step "Select the intended subscription; copy Subscription ID and Directory (tenant) ID from its overview."
capture_public AZURE_SUBSCRIPTION_ID "Public subscription UUID:"
capture_public AZURE_TENANT_ID "Public tenant UUID:"
open_url "https://learn.microsoft.com/en-us/azure/cosmos-db/free-tier"
step "Inspect all Cosmos accounts in this subscription. New service requires an unused free-tier slot. Never choose a paid fallback."
open_url "https://learn.microsoft.com/en-us/azure/container-apps/regions"
step "Choose a supported Consumption/Cosmos region, check quotas and create the dedicated resource group yourself."
capture_public LOCATION "Compact region code (for example eastus):"
capture_public AZURE_RESOURCE_GROUP "Public dedicated resource-group name:"
step "Manually register Microsoft.App, Microsoft.DocumentDB, Microsoft.ManagedIdentity, Microsoft.OperationalInsights, Microsoft.Insights and Microsoft.Consumption."
pause "Confirm subscription eligibility, region and dedicated resource group before continuing."

stage "Two protected GitHub environments"
open_url "https://github.com/Nortus222/claude-config/settings/environments"
step "Create hosted-image and hosted-production separately. Require an eligible reviewer distinct from the run initiator for each."
step "Select deployment branches/tags: selected branches; add exactly branch main and no tags or wildcard patterns."
step "Disable administrator bypass. Enable Prevent self review in BOTH environments; self approval must remain blocked."
note "No environments existed at the 2026-10-08 read-only check; prepare fails until reviewers, self-review prevention and exact main policy exist."
pause "Confirm both approval boundaries are configured."

stage "CI identity and exact Azure federation"
open_url "https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect"
step "In Entra ID, create a CI-only app/service principal, no client secret. Copy its Application (client) ID."
capture_public AZURE_CLIENT_ID "Public CI Application (client) UUID:"
open_url "https://docs.github.com/en/actions/reference/security/oidc#immutable-subject-claims"
step "Verify this repository's actual subject configuration and any organization/repository subject template first."
step "Federation issuer: https://token.actions.githubusercontent.com; audience: api://AzureADTokenExchange."
step "Legacy subject if actually configured: repo:Nortus222/claude-config:environment:hosted-production. Immutable-ID configuration requires its exact real subject; never use wildcards."
step "Manually grant resource-group deployment rights and subscription-level Microsoft.DocumentDB/databaseAccounts/read only for eligibility; see README for the complete read scopes."
step "In hosted-production environment Variables, enter AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_SUBSCRIPTION_ID and AZURE_RESOURCE_GROUP from this snapshot."
note "The template creates a different runtime UAMI. Never reuse CI as runtime identity or give it Owner/Graph discovery permissions."
pause "Confirm exact federation, least privilege and public environment variables."

stage "GitHub identity-only device-flow app"
open_url "https://github.com/settings/developers"
step "OAuth Apps: create/select the service app; supply owner-controlled homepage and callback URLs as GitHub requires."
step "Enable Device Flow in the app settings; copy Client ID only. This runtime requests no scope and requires no client secret."
capture_public GITHUB_CLIENT_ID "Public OAuth Client ID:"
note "Do not authorize a device flow or paste a client secret into this wizard. Real OAuth proof is a later authorized task."
pause "Confirm the app is identity-only and device flow enabled."

stage "Reviewed public config and first publication"
open_url "https://github.com/Nortus222/claude-config/blob/main/apps/service/infra/parameters.example.json"
step "Copy the example to parameters.production.json in a feature worktree; replace every placeholder with reviewed public values."
step "Set region, stable prefix, OAuth client ID, signup/allowlist, monthly currency amount/contacts and valid first-of-month budget date. Closed signup plus empty allowlist safely denies all."
step "Validate with validate.ts and a reviewed immutable digest, then review and merge public configuration to main through the normal PR process."
open_url "https://github.com/Nortus222/claude-config/actions/workflows/service-image.yml"
step "Only when separately authorized: manually publish reviewed main through hosted-image approval; record the resulting digest and source commit."
open_url "https://github.com/users/Nortus222/packages/container/claude-config-service/settings"
step "First packages default private: manually change this package to public before deployment; confirm anonymous availability."
step "Only when separately authorized: dispatch service-deploy on main with reviewed_commit, image_commit and image_ref; inspect prepare summary before hosted-production approval."
note "This wizard does not publish, deploy, authenticate or run acceptance. Issues #51 and #81 stay open until that later evidence exists."
pause "Review the README deployment and rollback checklist; retain only this public snapshot as needed."
finish
